### ISSUE TITLE
Does HyperMapper only accept python program as input?

### ISSUE THREAD

**Issue by yrq0208** [luinardi/hypermapper#15]
Hi all,

This is probably a very naive question, but does HyperMapper only accept python program as input? It seems all your examples are developed in python, does it accept C/C++ program as input?

Thank you in advance.

**Comment by luinardi** [comment]
HyperMapper has C++, Python, and Scala clients. 

There is a README provided in the C++ client implementation (https://github.com/luinardi/hypermapper/tree/master/example_scenarios/clients/cpp_client). 

This is a step-by-step example of the client-server mode: https://github.com/luinardi/hypermapper/wiki/Client%E2%80%90Server-Chakong%E2%80%90Haimes. 

Hope this helps.

**Comment by luinardi** [comment]
Hello, FYI the last PR included real variables in the C++ client, which finalizes the C++ client.
