### ISSUE TITLE
Input types

### ISSUE THREAD

**Issue by SandraHernandezH** [luinardi/hypermapper#18]
Hi! 
Is there any way to use the integer type input with a range of values and a single value outside this range, or maybe another type of input? 
I mean, adding an integer input 'x1' that takes values between [15, 50] and also 0. 
x1 ∈ {0} ∪ [15, 50]
I know this could be done with the ordinal input, but if the range is [10, 1000] it would be tedious to write all the possible input values.
Thanks!

**Comment by luinardi** [comment]
Hello, 

ordinal variables are the only way to go for that. If you are in trouble inputting too many values you can use a python script to print them and then copy-paste them into the JSON file. You can also produce the JSON file programmatically as in [this example](https://github.com/luinardi/hypermapper/blob/master/example_scenarios/demo/demo_jupyter_notebook2020.ipynb) which will avoid the copy-pasting. 

However, I wouldn't recommend having hundreds and hundreds of values in the range of one parameter. In my experience, you can prune those parameters to facilitate the optimization without losing much in terms of performance. This leads to having a thoughtful design of the search space. 

Please refer to this [guide](https://github.com/luinardi/hypermapper/wiki/Newbie-Guide) for suggestions on how to get the best performance with HyperMapper. 

Hope this helps.
