### ISSUE TITLE
local variable 'output_pareto_file' referenced before assignment

### ISSUE THREAD

**Issue by SandraHernandezH** [luinardi/hypermapper#21]
Hi, 
I think you have an issue in `plot_dse.py` when input files are used as argument. A reference to the variable 'output_pareto_file' is made outside the if condition where this variable is set to a value. I think you only want to append values to 'list_of_pairs_of_files' in case there is no input files. Therefore, the instruction in line 72 - [here](https://github.com/luinardi/hypermapper/blob/master/scripts/plot_dse.py#L72) - should be inside the first if condition. 
Hope I'm not wrong

**Comment by arturluis** [comment]
Hi @SandraHernandezH, 

Thank you for bringing this to our attention. I have just pushed a fix to this issue. Can you pull the latest version and see if the problem persists?

**Comment by SandraHernandezH** [comment]
Thanks @arturluis!
The problem is now solved.

**Comment by arturluis** [comment]
Hello @SandraHernandezH,

Glad that it addressed your issue, feel free to open other issues if you need. Also, If you want to have a more direct communication channel with the development team, you can also join the HyperMapper slack channel: `hypermapper.slack.com`

**Comment by SandraHernandezH** [comment]
Hi @arturluis,
Thank you for the invitation. I am currently working with HyperMapper and I am really interested in joining slack channel but I have not succeeded . I don't know if I need some kind of authorization from you, but I am trying to join with the same email account I have on GitHub.

**Comment by arturluis** [comment]
Hello @SandraHernandezH ,

Can you try to join using the link below and let me know if it wiorks?

https://join.slack.com/t/hypermapper/shared_invite/zt-i3zdcs6v-4SfPbqWnBWKRphHUpJwgqA
