### ISSUE TITLE
Intermediate output values for the optimization 

### ISSUE THREAD

**Issue by mumair5393** [luinardi/hypermapper#24]
Hi,

I was doing some experiments using hypermapper. During the optimzation the system crashed. I tried warm starting hypermapper and figured out that it requires output.csv file for that, which is only generated at the end of optimization as far as I noticed. I think it  will be better to update the output.csv file after each iteration rather than generating the entire output file at the end of optimization, this way the work which is done previously by hypermapper will not be lost if something unforeseeable happens during the run.

Thanks

**Comment by arturluis** [comment]
Hi @mumair5393,

That is curious, HyperMapper does generate the output.csv file incrementally. It creates the file at the beginning of optimization and updates it each iteration. Are you positive the .csv file was not generated? Also, are you using the latest version of HyperMapper?

If so, can you share some details of your optimization application so I can investigate if there is some issue with the code? E.g. Are you using any features such as feasibility constraints, prior injection, client-server mode, etc.? Also, did you change any of the defaults provided by HyperMapper?

Best,
