### ISSUE TITLE
Out-of-range issue in example_scenarios/clients/python/client-server_chakong_haimes.py 

### ISSUE THREAD

**Issue by mpett** [luinardi/hypermapper#26]
Hi, I'm getting an out-of-range issue here, using the default json parameter file.

ubuntu@martin-test:~/hypermapper$ python3 example_scenarios/clients/python/client-server_chakong_haimes.py 
['python', 'scripts/hypermapper.py', 'example_scenarios/clients/python/client-server_chakong_haimes_scenario.json']
Iteration 0
Traceback (most recent call last):
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 61, in <module>
    main()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 57, in main
    communication_protocol_chakong_haimes_hypermapper()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 41, in communication_protocol_chakong_haimes_hypermapper
    num_of_eval_requests = int(request.split(' ')[1])  # Get the #_of_evaluation_requests
IndexError: list index out of range

**Comment by arturluis** [comment]
Hi @mpett,

It seems that the invoked HyperMapper process ran into an issue. Can you run the hypermapper script directly and report the output?
```
python scripts/hypermapper.py example_scenarios/clients/python/client-server_chakong_haimes_scenario.json
```

Can you also double-check if the HYPERMAPPER_HOME environment variable is properly set?

**Comment by mpett** [comment]
Hi @arturluis, thanks for your reply.

It gives me the following output:

Collecting cython
  Downloading https://files.pythonhosted.org/packages/19/49/91ebe4a00bf894d08dd9680cd9dfb05936eb2848eebd9402b43885aa74cf/Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 648kB/s 
Installing collected packages: cython
Successfully installed cython-0.29.21
ubuntu@martin-test:~/hypermapper$ python3 scripts/hypermapper.py example_scenarios/clients/python/client-server_chakong_haimes_scenario.json
warning in stationary: failed to import cython module: falling back to numpy
warning in coregionalize: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy
Request 20
x1,x2
0,0
19.768362632345763,-0.1196259019938779
11.575299907763736,-4.128151075627542
2.060460639926106,-18.712590721971587
11.591738682484944,-15.368613620251063
10.39420161623105,-7.220048353203039
-17.50805991309743,-8.771327010179634
-15.355625052166062,14.32189396948688
-12.146327161124788,9.679312467809158
-3.8146590520274053,-18.497024424850096
18.999255595079468,-19.86473971787587
17.70153751066679,13.257005873414414
7.508472448651247,15.323222347627429
-17.591282751240485,-10.627271752455245
-14.507184920438887,18.1531081754109
5.955950837481279,-2.9901660089618254
13.140682289516697,-4.337603020036447
13.921155175218352,-7.377003772660025
-10.897135321101901,0.3006712896573873
-1.755247673769091,9.350369349016269

**Comment by mpett** [comment]
ubuntu@martin-test:~$ cd $HYPERMAPPER_HOME
ubuntu@martin-test:~/hypermapper$ pwd
/home/ubuntu/hypermapper
ubuntu@martin-test:~/hypermapper$

**Comment by mpett** [comment]
Running it again and double-checking the home path:

ubuntu@martin-test:~/hypermapper$ sudo python3 example_scenarios/clients/python/client-server_chakong_haimes.py 
['python', 'scripts/hypermapper.py', 'example_scenarios/clients/python/client-server_chakong_haimes_scenario.json']
Iteration 0

Traceback (most recent call last):
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 62, in <module>
    main()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 58, in main
    communication_protocol_chakong_haimes_hypermapper()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 42, in communication_protocol_chakong_haimes_hypermapper
    num_of_eval_requests =  int(request.split(' ')[0])  # Get the #_of_evaluation_requests
ValueError: invalid literal for int() with base 10: ''

ubuntu@martin-test:~/hypermapper$ cd $HYPERMAPPER_HOME
ubuntu@martin-test:~/hypermapper$ cd ~
ubuntu@martin-test:~$ cd $HYPERMAPPER_HOME
ubuntu@martin-test:~/hypermapper$ pwd
/home/ubuntu/hypermapper

**Comment by mpett** [comment]
`ubuntu@martin-test:~/hypermapper$ sudo python3 example_scenarios/clients/python/client-server_chakong_haimes.py 
['python', 'scripts/hypermapper.py', 'example_scenarios/clients/python/client-server_chakong_haimes_scenario.json']
Iteration 0

Traceback (most recent call last):
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 62, in <module>
    main()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 58, in main
    communication_protocol_chakong_haimes_hypermapper()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 42, in communication_protocol_chakong_haimes_hypermapper
    num_of_eval_requests =  int(request.split(' ')[1])  # Get the #_of_evaluation_requests
IndexError: list index out of range
ubuntu@martin-test:~/hypermapper$ cd ~
ubuntu@martin-test:~$ cd $HYPERMAPPER_HOME
ubuntu@martin-test:~/hypermapper$ pwd
/home/ubuntu/hypermapper
ubuntu@martin-test:~/hypermapper$ `

**Comment by mpett** [comment]
ubuntu@martin-test:~/hypermapper$ sudo python3 example_scenarios/clients/python/client-server_chakong_haimes.py 
['python', 'scripts/hypermapper.py', 'example_scenarios/clients/python/client-server_chakong_haimes_scenario.json']
Iteration 0

Traceback (most recent call last):
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 62, in <module>
    main()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 58, in main
    communication_protocol_chakong_haimes_hypermapper()
  File "example_scenarios/clients/python/client-server_chakong_haimes.py", line 42, in communication_protocol_chakong_haimes_hypermapper
    num_of_eval_requests =  int(request.split(' ')[1])  # Get the #_of_evaluation_requests
IndexError: list index out of range
ubuntu@martin-test:~/hypermapper$ cd ~
ubuntu@martin-test:~$ cd $HYPERMAPPER_HOME
ubuntu@martin-test:~/hypermapper$ pwd
/home/ubuntu/hypermapper
ubuntu@martin-test:~/hypermapper$

**Comment by arturluis** [comment]
Thanks @mpett ,

These lines are likely what is causing an issue with client-server mode:
```
warning in stationary: failed to import cython module: falling back to numpy
warning in coregionalize: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy
```
Once the client-receives back these lines it does not know how to handle them. It seems there is something preventing GPy from recognizing your Cython installation. Note that the call inside the chakong-haimes_client_server.py file is:
```
python scripts/hypermapper.py example_scenarios/clients/python/client-server_chakong_haimes_scenario.json
```
which, in a system with both Python2 and Python3, might default to Python2. Can you double check whether Python is calling Python3? If not, try changing this line ([line 29 in chakong-haimes_client_server.py](https://github.com/luinardi/hypermapper/blob/59f7ba05a53fed5e8175effa13d1620bae16b83a/example_scenarios/clients/python/client-server_chakong_haimes.py#L29)):
```
cmd = ["python", "scripts/hypermapper.py", "example_scenarios/clients/python/client-server_chakong_haimes_scenario.json"]
```
to
```
cmd = ["python3", "scripts/hypermapper.py", "example_scenarios/clients/python/client-server_chakong_haimes_scenario.json"]
```
