### ISSUE TITLE
Help message needs updating

### ISSUE THREAD

**Issue by adelejjeh** [luinardi/hypermapper#39]
The help message that gets printed out with the new command line tool when invoked with `hypermapper --help` is outdated.
Message output:
```
❯ hypermapper --help
################################################
### Example:
### hypermapper example_scenarios/spatial/BlackScholes_scenario.json
################################################
```
The file `example_scenarios/spatial/BlackScholes_scenario.json` doesn't exist.

**Comment by arturluis** [comment]
Hi @adelejjeh,

Thanks for bringing this up, we have updated the help message that is printed in the latest release.
