### ISSUE TITLE
Instructions for setting up Spatial use-case demo are breaking

### ISSUE THREAD

**Issue by adelejjeh** [luinardi/hypermapper#5]
There seems to be something incorrect about the instructions for setting up Spatial in the [wiki page](https://github.com/luinardi/hypermapper/wiki/The-Spatial-Use-Case). Specifically, I am using Ubuntu 20.04 and the packages `sbt` and `isl` cannot be found by `apt`.

**Comment by mattfel1** [comment]
Hi.  I haven't tried on this version of Ubuntu, but can you try these more detailed installation steps for these two dependencies?

SBT: https://www.scala-sbt.org/download.html
ISL: http://isl.gforge.inria.fr//user.html#Installation

**Comment by adelejjeh** [comment]
Thanks Matt. What version of Ubuntu have you guys tested on? I've also tested on 18.04 and they also don't work. Also, for `isl` it seems like the package is called `libisl-dev`.

**Comment by mattfel1** [comment]
Whoops.  I updated the isl install command on the wiki.  I've only used ubuntu 18.04.  The problem with sbt is that it needs these steps the first time around.  Does it work after you run these?

```
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
sudo apt-get update
```

**Comment by adelejjeh** [comment]
Yes exactly! The source has to be added to apt sources before you can install it using `apt install sbt`. Might be worth adding to the wiki in case someone else faces the same problem.

**Comment by arturluis** [comment]
Thank you for pointing this out, we have updated the wiki to include these steps.
