### ISSUE TITLE
numpy.int64 types sometimes passed in for integer parameters

### ISSUE THREAD

**Issue by noahsherrill** [luinardi/hypermapper#71]
I have noticed that for an integer parameter, HyperMapper sometimes passes a Python `int` type and sometimes a `numpy.int64` type. I have not observed this behavior for ordinal parameters, which appear to only use the `int` type. This is causing an issue for my application because the parameter values are sent to other execution environments where `numpy` may not be installed. Is sometimes, but not always, using the `numpy.int64` type the intended behavior?

To observe this, I used the following configuration file:
```
{
  "application_name": "test",
  "optimization_objectives": ["Value"],
  "optimization_iterations": 10,
  "input_parameters": {
    "x1": {
      "parameter_type": "integer",
      "values": [0, 50],
      "parameter_default": 0
    },
    "x2": {
      "parameter_type": "integer",
      "values": [0, 100],
      "parameter_default": 0
    }
  }
}
```
The code is as follows:
```
from hypermapper import optimizer

def test_function(X):
    x1 = X['x1']
    x2 = X['x2']

    print("x1 param type: %s, x2 param type: %s" % (type(x1), type(x2)))

    return x1 ** 2 - x1 * x2 + 35


optimizer.optimize("config_test.json", test_function)
```
The output is as follows:
```
Design of experiment phase, number of new doe samples = 10 .......
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
0,0,35,18
1,86,-50,18
30,62,-925,18
2,9,21,18
1,100,-64,18
44,35,431,18
41,5,1511,18
8,33,-165,19
38,79,-1523,19
35,45,-315,19


End of doe/resume phase, the number of evaluated configurations is: 10

Starting optimization iteration 1
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
39,58,-706,741

Starting optimization iteration 2
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
41,56,-580,1439

Starting optimization iteration 3
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
49,71,-1043,2116

Starting optimization iteration 4
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
42,62,-805,2833

Starting optimization iteration 5
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
41,79,-1523,3569

Starting optimization iteration 6
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
41,78,-1482,4258

Starting optimization iteration 7
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
41,80,-1564,4867

Starting optimization iteration 8
x1 param type: <class 'int'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
47,44,176,4911

Starting optimization iteration 9
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'numpy.int64'>
x1,x2,Value,Timestamp
46,78,-1437,5563

Starting optimization iteration 10
x1 param type: <class 'numpy.int64'>, x2 param type: <class 'int'>
x1,x2,Value,Timestamp
43,79,-1513,6178

End of Bayesian Optimization
Best point found:
x1,x2,Value
41,80,-1564

End of HyperMapper
```

**Comment by arturluis** [comment]
Hey @noahsherrill ,

Can you share some details on the setup you have now?

I ask because HyperMapper depends on NumPy for some steps internally, so the system running HyperMapper would need to have NumPy anyway. Are you running a sort of multi-machine experiment where parameters are packed and sent to another environment for evaluation?

I would like to understand better the setup and the issue before proposing a solution

Best,

**Comment by noahsherrill** [comment]
Yes, what you stated about the parameters being packed and sent to another environment for evaluation is exactly right. We have different applications running in different environments that each yield a subset of the objective values. The environment that is executing HyperMapper does indeed have `numpy` installed, but some of the evaluation environments don't. We were actually able to run successfully before, as we were only using ordinal parameters. However, when we recently added some integer parameters, we ran into issues, and I traced it to the `numpy.int64` type being sometimes used for the integer parameters.

We can potentially address this on our end if this is the way HyperMapper is meant to work. I was just a little surprised to see two similar, but distinct, types used for the same parameter, so I wanted to clarify first.

**Comment by arturluis** [comment]
Hi @noahsherrill ,

So sorry it took us long to get back to you. That may happen sometimes because of the internals of HM, in short, it boils down to where these configurations were generated (e.g. during a RS step or during acquisition function optimization). We use different methods in those steps and some require numpy while others don't. I think it would be safest if you converted it on your side if possible, since I can't guarantee we will converge to one type in the near future. 

However, if this becomes an issue that you can't handle on your side, let us know and we will see if we can address it inside HM.

Thanks for pointing this out!

**Comment by noahsherrill** [comment]
Thank you for the clarification. We will convert the types before sending them to the evaluation environments. There's no need to apologize for the delay. I'm grateful you provided the tool as open source and for what support you are able to provide with your valuable and limited time.
