### ISSUE TITLE
What is the maximum problem size/# parameters recommended?

### ISSUE THREAD

**Issue by ArmandB** [luinardi/hypermapper#83]
What is the maximum problem size/# parameters recommended to be used with Hypermapper?

The maximum I saw in an example is 13 hyperparameters (GEMM) w/ a problem size of 2.4x10^11 (GDA). Would it help to increase parameters such as "number_of_trees"?

One technique I've used to try and reduce the problem size is to use ordinal parameters instead of integer parameters so increase the gap between the setting values.

Sorry if this isn't the right place to ask this question.

All the best!

**Comment by arturluis** [comment]
Hey @ArmandB ,

We have tried HyperMapper with up to 100 parameters (iirc) in some test benchmarks with decent success, so it can be used for pretty large problems. That said, I would expect it to perform better when kept at around 15 parameters or less. Increasing the number of trees can help for larger search spaces, but it is hard to say how much it will help as there are other factors to consider (e.g. parameter types and search space complexity). Other strategies like a larger design of experiments phase and increasing the parameters of the local search might help as well (do note that this might also cause HyperMapper to take longer to run). 

Your technique of reducing the number of possible values from an integer range to an ordinal list is definitely a good approach. That is something we often recommend to users when there are large integer ranges in the search space.

Feel free to ask away if you have any other questions!

Best!
Artur Souza
