### ISSUE TITLE
Categorical Parameters broken in the `hypermapper-v3` branch

### ISSUE THREAD

**Issue by panzerox123** [luinardi/hypermapper#93]
Hey folks,
Categorical parameters don't work while using the `hypermapper-v3` branch, here are the changes that I had to make in order to get it working:

**File: hypermapper/param/parameters.py:**
- `convert` does not return string value -> Line 639 needs to return `self.string_values...​` and not `self.values...​`
- Constructor for `CategoricalParameter` does not create the correct `val_indices` dictionary -> Line 552 must be in the form `{i.item(): i...`​ and not `{i: i...`​

Thanks,
Kunal Bhat

**Comment by ErikOrm** [comment]
Thanks! I added the proposed fixes and added a test for categorical variables in the test suite.
